name: 'App deploy action script to ENONIC XP'
description: 'Github action script to be used for app deployment'
inputs:
  url:
    description: 'URL to XP instance'
    required: true
  username:
    description: 'user name'
    required: false
  password:
    description: 'password of deploy user'
    required: false
  client_key:
    description: 'Client key, required only for MTLS session'
    required: false
  client_cert:
    description: 'Client cert, required only for MTLS session'
    required: false
  cred_file:
    description: 'A service account key represented as a JSON string, containing the properties "algorithm", "kid", "principalKey", and "privateKey", used to generate a JWT token for authentication'
    required: false
  app_jar:
    description: 'Path and name of the app to be deployed'
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    ENONIC_CLI_REMOTE_URL: ${{ inputs.url }}
    XP_USERNAME: ${{ inputs.username }}
    XP_PASSWORD: ${{ inputs.password }}
    APP_JAR: ${{ inputs.app_jar }}
    CLIENT_KEY: ${{ inputs.client_key }}
    CLIENT_CERT: ${{ inputs.client_cert }}
    CRED_FILE: ${{ inputs.cred_file }}
